language: node_js
node_js:
  - 14.4.0

branches:
  only:
    - /.*/

cache:
  yarn: true

install:
  - yarn install

jobs:
  include:
    - stage: test
      name: backend node
      script:
        - yarn test
