language: node_js
node_js:
  - 14.4.0

branches:
  only:
    - master

cache:
  yarn: true

install:
  - yarn install

jobs:
  include:
    - stage: test
      name: backend node
      script:
        - cd /api
        - yarn test
        - yarn test:e2e
        - yarn test:cov

notifications:
  email:
    recipients:
      - wnsqlehlswk@naver.com
    on_success: change
    on_failure: always
