import {MigrationInterface, QueryRunner} from "typeorm";

export class prepareSchema1603608484576 implements MigrationInterface {
    name = 'prepareSchema1603608484576'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("CREATE TABLE `notice` (`id` int NOT NULL AUTO_INCREMENT, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `deleted_at` datetime(6) NULL, `content` text NOT NULL, `is_read` tinyint NOT NULL DEFAULT 0, `user_id` int NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `teams` (`id` int NOT NULL AUTO_INCREMENT, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `deleted_at` datetime(6) NULL, `name` varchar(255) NOT NULL, `description` text NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `edit_histories` (`id` int NOT NULL AUTO_INCREMENT, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `deleted_at` datetime(6) NULL, `ref_id` bigint NULL, `ref_type` bigint NULL, `edit_type` smallint NOT NULL, `prev_id` int NULL, `user_id` int NULL, UNIQUE INDEX `REL_48576009c45cfe3d29e290f881` (`prev_id`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `user_oauths` (`id` int NOT NULL AUTO_INCREMENT, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `deleted_at` datetime(6) NULL, `type` bigint NOT NULL, `auth_id` text NOT NULL, `user_id` int NULL, UNIQUE INDEX `REL_e8134bca23f6ae0b95ca5c401c` (`user_id`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `scalars` (`id` int NOT NULL AUTO_INCREMENT, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `deleted_at` datetime(6) NULL, `value` double NOT NULL, `index` int NOT NULL, `column_id` int NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `vectors` (`id` int NOT NULL AUTO_INCREMENT, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `deleted_at` datetime(6) NULL, `name` varchar(255) NOT NULL, `index` int NOT NULL, `expression_id` int NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `tags` (`id` int NOT NULL AUTO_INCREMENT, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `deleted_at` datetime(6) NULL, `name` varchar(255) NOT NULL, `expression_id` int NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `expression_settings` (`id` int NOT NULL AUTO_INCREMENT, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `deleted_at` datetime(6) NULL, `is_public` tinyint NOT NULL DEFAULT 0, `is_locked` tinyint NOT NULL DEFAULT 0, `expression_id` int NULL, UNIQUE INDEX `REL_3a5ace99268077a859527db1e7` (`expression_id`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `user_profile_images` (`id` int NOT NULL AUTO_INCREMENT, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `deleted_at` datetime(6) NULL, `image_id` int NULL, `user_id` int NULL, UNIQUE INDEX `REL_2dcb777c05a94bf80fa045619a` (`image_id`), UNIQUE INDEX `REL_c10d5d5b70a32fa688c0d9736e` (`user_id`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `images` (`id` int NOT NULL AUTO_INCREMENT, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `deleted_at` datetime(6) NULL, `url` text NOT NULL, `extension` varchar(255) NOT NULL, `path` text NOT NULL, `type` int NOT NULL, `file_name` text NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `expression_thumbnail_images` (`id` int NOT NULL AUTO_INCREMENT, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `deleted_at` datetime(6) NULL, `expression_id` int NULL, `image_id` int NULL, UNIQUE INDEX `REL_9ae9357b790f252750336649f2` (`expression_id`), UNIQUE INDEX `REL_971bec38ed03213c6d7a6f4a88` (`image_id`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `expressions` (`id` int NOT NULL AUTO_INCREMENT, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `deleted_at` datetime(6) NULL, `type` tinyint NOT NULL, `name` varchar(255) NOT NULL, `content` text NOT NULL, `description` text NOT NULL, `like_count` int NOT NULL DEFAULT 0, `is_forked` tinyint NOT NULL DEFAULT 0, `fork_count` int NOT NULL DEFAULT 0, `user_id` int NULL, `origin_id` int NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `user_settings` (`id` int NOT NULL AUTO_INCREMENT, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `deleted_at` datetime(6) NULL, `user_id` int NULL, UNIQUE INDEX `REL_4ed056b9344e6f7d8d46ec4b30` (`user_id`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `roles` (`id` int NOT NULL AUTO_INCREMENT, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `deleted_at` datetime(6) NULL, `name` varchar(10) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `users` (`id` int NOT NULL AUTO_INCREMENT, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `deleted_at` datetime(6) NULL, `name` varchar(255) NOT NULL, `email` varchar(255) NULL DEFAULT NULL, `description` text NULL DEFAULT NULL, `is_anonymous` tinyint NOT NULL DEFAULT 0, `liked_count` int NOT NULL DEFAULT 0, `forked_count` int NOT NULL DEFAULT 0, UNIQUE INDEX `IDX_97672ac88f789774dd47f7c8be` (`email`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `comments` (`id` int NOT NULL AUTO_INCREMENT, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `deleted_at` datetime(6) NULL, `content` text NOT NULL, `ref_type` bigint NULL, `ref_id` bigint NULL, `user_id` int NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `edit_history_value_bigints` (`id` int NOT NULL AUTO_INCREMENT, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `deleted_at` datetime(6) NULL, `value` bigint NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `edit_history_value_varchars` (`id` int NOT NULL AUTO_INCREMENT, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `deleted_at` datetime(6) NULL, `value` varchar(255) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `user_likes` (`to_user_id` bigint NOT NULL, `from_user_id` bigint NOT NULL, `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `deleted_at` datetime(6) NULL, PRIMARY KEY (`to_user_id`, `from_user_id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `user_team` (`team_id` int NOT NULL, `user_id` int NOT NULL, INDEX `IDX_ab79684958e64041b68533a934` (`team_id`), INDEX `IDX_66f79a319649fbcc7d5bd1f690` (`user_id`), PRIMARY KEY (`team_id`, `user_id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `expression_likes` (`to_expression_id` int NOT NULL, `from_user_id` int NOT NULL, INDEX `IDX_7461087580d7888ddb57e09754` (`to_expression_id`), INDEX `IDX_a2e4c318331840ed4e0b3b7109` (`from_user_id`), PRIMARY KEY (`to_expression_id`, `from_user_id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `user_role` (`role_id` int NOT NULL, `user_id` int NOT NULL, INDEX `IDX_32a6fc2fcb019d8e3a8ace0f55` (`role_id`), INDEX `IDX_d0e5815877f7395a198a4cb0a4` (`user_id`), PRIMARY KEY (`role_id`, `user_id`)) ENGINE=InnoDB");
        await queryRunner.query("ALTER TABLE `user_likes` DROP COLUMN `created_at`");
        await queryRunner.query("ALTER TABLE `user_likes` DROP COLUMN `updated_at`");
        await queryRunner.query("ALTER TABLE `user_likes` DROP COLUMN `deleted_at`");
        await queryRunner.query("ALTER TABLE `user_likes` ADD `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `user_likes` ADD `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `user_likes` ADD `deleted_at` datetime(6) NULL");
        await queryRunner.query("ALTER TABLE `user_likes` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `user_likes` ADD PRIMARY KEY (`from_user_id`)");
        await queryRunner.query("ALTER TABLE `user_likes` DROP COLUMN `to_user_id`");
        await queryRunner.query("ALTER TABLE `user_likes` ADD `to_user_id` int NOT NULL");
        await queryRunner.query("ALTER TABLE `user_likes` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `user_likes` ADD PRIMARY KEY (`from_user_id`, `to_user_id`)");
        await queryRunner.query("ALTER TABLE `user_likes` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `user_likes` ADD PRIMARY KEY (`to_user_id`)");
        await queryRunner.query("ALTER TABLE `user_likes` DROP COLUMN `from_user_id`");
        await queryRunner.query("ALTER TABLE `user_likes` ADD `from_user_id` int NOT NULL");
        await queryRunner.query("ALTER TABLE `user_likes` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `user_likes` ADD PRIMARY KEY (`to_user_id`, `from_user_id`)");
        await queryRunner.query("CREATE INDEX `IDX_db120332969a51db7d76a46912` ON `user_likes` (`to_user_id`)");
        await queryRunner.query("CREATE INDEX `IDX_d2d8d1cf1a5354af1284ce91df` ON `user_likes` (`from_user_id`)");
        await queryRunner.query("ALTER TABLE `notice` ADD CONSTRAINT `FK_3667d24b06587be480a9015d3b2` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `edit_histories` ADD CONSTRAINT `FK_48576009c45cfe3d29e290f881d` FOREIGN KEY (`prev_id`) REFERENCES `edit_histories`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `edit_histories` ADD CONSTRAINT `FK_9988eac307b55a3344dea48d424` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user_oauths` ADD CONSTRAINT `FK_e8134bca23f6ae0b95ca5c401c8` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `scalars` ADD CONSTRAINT `FK_8b0b62f607e8012081edb070ace` FOREIGN KEY (`column_id`) REFERENCES `vectors`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `vectors` ADD CONSTRAINT `FK_b409d94ffebb695975a91d4736f` FOREIGN KEY (`expression_id`) REFERENCES `expressions`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `tags` ADD CONSTRAINT `FK_6adde8aca3180d1ba08b6e8ed8f` FOREIGN KEY (`expression_id`) REFERENCES `expressions`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `expression_settings` ADD CONSTRAINT `FK_3a5ace99268077a859527db1e70` FOREIGN KEY (`expression_id`) REFERENCES `expressions`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user_profile_images` ADD CONSTRAINT `FK_2dcb777c05a94bf80fa045619a8` FOREIGN KEY (`image_id`) REFERENCES `images`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user_profile_images` ADD CONSTRAINT `FK_c10d5d5b70a32fa688c0d9736ed` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `expression_thumbnail_images` ADD CONSTRAINT `FK_9ae9357b790f252750336649f24` FOREIGN KEY (`expression_id`) REFERENCES `expressions`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `expression_thumbnail_images` ADD CONSTRAINT `FK_971bec38ed03213c6d7a6f4a884` FOREIGN KEY (`image_id`) REFERENCES `images`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `expressions` ADD CONSTRAINT `FK_4125687ae2b311b6d6d5774c2fa` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `expressions` ADD CONSTRAINT `FK_695f9f1eb1b188d8bd3612cb1fa` FOREIGN KEY (`origin_id`) REFERENCES `expressions`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user_settings` ADD CONSTRAINT `FK_4ed056b9344e6f7d8d46ec4b302` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `comments` ADD CONSTRAINT `FK_4c675567d2a58f0b07cef09c13d` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user_team` ADD CONSTRAINT `FK_ab79684958e64041b68533a9343` FOREIGN KEY (`team_id`) REFERENCES `teams`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user_team` ADD CONSTRAINT `FK_66f79a319649fbcc7d5bd1f6901` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `expression_likes` ADD CONSTRAINT `FK_7461087580d7888ddb57e09754b` FOREIGN KEY (`to_expression_id`) REFERENCES `expressions`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `expression_likes` ADD CONSTRAINT `FK_a2e4c318331840ed4e0b3b71097` FOREIGN KEY (`from_user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user_role` ADD CONSTRAINT `FK_32a6fc2fcb019d8e3a8ace0f55f` FOREIGN KEY (`role_id`) REFERENCES `roles`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user_role` ADD CONSTRAINT `FK_d0e5815877f7395a198a4cb0a46` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user_likes` ADD CONSTRAINT `FK_db120332969a51db7d76a469121` FOREIGN KEY (`to_user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `user_likes` ADD CONSTRAINT `FK_d2d8d1cf1a5354af1284ce91dfc` FOREIGN KEY (`from_user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("ALTER TABLE `user_likes` DROP FOREIGN KEY `FK_d2d8d1cf1a5354af1284ce91dfc`");
        await queryRunner.query("ALTER TABLE `user_likes` DROP FOREIGN KEY `FK_db120332969a51db7d76a469121`");
        await queryRunner.query("ALTER TABLE `user_role` DROP FOREIGN KEY `FK_d0e5815877f7395a198a4cb0a46`");
        await queryRunner.query("ALTER TABLE `user_role` DROP FOREIGN KEY `FK_32a6fc2fcb019d8e3a8ace0f55f`");
        await queryRunner.query("ALTER TABLE `expression_likes` DROP FOREIGN KEY `FK_a2e4c318331840ed4e0b3b71097`");
        await queryRunner.query("ALTER TABLE `expression_likes` DROP FOREIGN KEY `FK_7461087580d7888ddb57e09754b`");
        await queryRunner.query("ALTER TABLE `user_team` DROP FOREIGN KEY `FK_66f79a319649fbcc7d5bd1f6901`");
        await queryRunner.query("ALTER TABLE `user_team` DROP FOREIGN KEY `FK_ab79684958e64041b68533a9343`");
        await queryRunner.query("ALTER TABLE `comments` DROP FOREIGN KEY `FK_4c675567d2a58f0b07cef09c13d`");
        await queryRunner.query("ALTER TABLE `user_settings` DROP FOREIGN KEY `FK_4ed056b9344e6f7d8d46ec4b302`");
        await queryRunner.query("ALTER TABLE `expressions` DROP FOREIGN KEY `FK_695f9f1eb1b188d8bd3612cb1fa`");
        await queryRunner.query("ALTER TABLE `expressions` DROP FOREIGN KEY `FK_4125687ae2b311b6d6d5774c2fa`");
        await queryRunner.query("ALTER TABLE `expression_thumbnail_images` DROP FOREIGN KEY `FK_971bec38ed03213c6d7a6f4a884`");
        await queryRunner.query("ALTER TABLE `expression_thumbnail_images` DROP FOREIGN KEY `FK_9ae9357b790f252750336649f24`");
        await queryRunner.query("ALTER TABLE `user_profile_images` DROP FOREIGN KEY `FK_c10d5d5b70a32fa688c0d9736ed`");
        await queryRunner.query("ALTER TABLE `user_profile_images` DROP FOREIGN KEY `FK_2dcb777c05a94bf80fa045619a8`");
        await queryRunner.query("ALTER TABLE `expression_settings` DROP FOREIGN KEY `FK_3a5ace99268077a859527db1e70`");
        await queryRunner.query("ALTER TABLE `tags` DROP FOREIGN KEY `FK_6adde8aca3180d1ba08b6e8ed8f`");
        await queryRunner.query("ALTER TABLE `vectors` DROP FOREIGN KEY `FK_b409d94ffebb695975a91d4736f`");
        await queryRunner.query("ALTER TABLE `scalars` DROP FOREIGN KEY `FK_8b0b62f607e8012081edb070ace`");
        await queryRunner.query("ALTER TABLE `user_oauths` DROP FOREIGN KEY `FK_e8134bca23f6ae0b95ca5c401c8`");
        await queryRunner.query("ALTER TABLE `edit_histories` DROP FOREIGN KEY `FK_9988eac307b55a3344dea48d424`");
        await queryRunner.query("ALTER TABLE `edit_histories` DROP FOREIGN KEY `FK_48576009c45cfe3d29e290f881d`");
        await queryRunner.query("ALTER TABLE `notice` DROP FOREIGN KEY `FK_3667d24b06587be480a9015d3b2`");
        await queryRunner.query("DROP INDEX `IDX_d2d8d1cf1a5354af1284ce91df` ON `user_likes`");
        await queryRunner.query("DROP INDEX `IDX_db120332969a51db7d76a46912` ON `user_likes`");
        await queryRunner.query("ALTER TABLE `user_likes` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `user_likes` ADD PRIMARY KEY (`to_user_id`)");
        await queryRunner.query("ALTER TABLE `user_likes` DROP COLUMN `from_user_id`");
        await queryRunner.query("ALTER TABLE `user_likes` ADD `from_user_id` bigint NOT NULL");
        await queryRunner.query("ALTER TABLE `user_likes` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `user_likes` ADD PRIMARY KEY (`from_user_id`, `to_user_id`)");
        await queryRunner.query("ALTER TABLE `user_likes` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `user_likes` ADD PRIMARY KEY (`from_user_id`)");
        await queryRunner.query("ALTER TABLE `user_likes` DROP COLUMN `to_user_id`");
        await queryRunner.query("ALTER TABLE `user_likes` ADD `to_user_id` bigint NOT NULL");
        await queryRunner.query("ALTER TABLE `user_likes` DROP PRIMARY KEY");
        await queryRunner.query("ALTER TABLE `user_likes` ADD PRIMARY KEY (`to_user_id`, `from_user_id`)");
        await queryRunner.query("ALTER TABLE `user_likes` DROP COLUMN `deleted_at`");
        await queryRunner.query("ALTER TABLE `user_likes` DROP COLUMN `updated_at`");
        await queryRunner.query("ALTER TABLE `user_likes` DROP COLUMN `created_at`");
        await queryRunner.query("ALTER TABLE `user_likes` ADD `deleted_at` datetime(6) NULL");
        await queryRunner.query("ALTER TABLE `user_likes` ADD `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `user_likes` ADD `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("DROP INDEX `IDX_d0e5815877f7395a198a4cb0a4` ON `user_role`");
        await queryRunner.query("DROP INDEX `IDX_32a6fc2fcb019d8e3a8ace0f55` ON `user_role`");
        await queryRunner.query("DROP TABLE `user_role`");
        await queryRunner.query("DROP INDEX `IDX_a2e4c318331840ed4e0b3b7109` ON `expression_likes`");
        await queryRunner.query("DROP INDEX `IDX_7461087580d7888ddb57e09754` ON `expression_likes`");
        await queryRunner.query("DROP TABLE `expression_likes`");
        await queryRunner.query("DROP INDEX `IDX_66f79a319649fbcc7d5bd1f690` ON `user_team`");
        await queryRunner.query("DROP INDEX `IDX_ab79684958e64041b68533a934` ON `user_team`");
        await queryRunner.query("DROP TABLE `user_team`");
        await queryRunner.query("DROP TABLE `user_likes`");
        await queryRunner.query("DROP TABLE `edit_history_value_varchars`");
        await queryRunner.query("DROP TABLE `edit_history_value_bigints`");
        await queryRunner.query("DROP TABLE `comments`");
        await queryRunner.query("DROP INDEX `IDX_97672ac88f789774dd47f7c8be` ON `users`");
        await queryRunner.query("DROP TABLE `users`");
        await queryRunner.query("DROP TABLE `roles`");
        await queryRunner.query("DROP INDEX `REL_4ed056b9344e6f7d8d46ec4b30` ON `user_settings`");
        await queryRunner.query("DROP TABLE `user_settings`");
        await queryRunner.query("DROP TABLE `expressions`");
        await queryRunner.query("DROP INDEX `REL_971bec38ed03213c6d7a6f4a88` ON `expression_thumbnail_images`");
        await queryRunner.query("DROP INDEX `REL_9ae9357b790f252750336649f2` ON `expression_thumbnail_images`");
        await queryRunner.query("DROP TABLE `expression_thumbnail_images`");
        await queryRunner.query("DROP TABLE `images`");
        await queryRunner.query("DROP INDEX `REL_c10d5d5b70a32fa688c0d9736e` ON `user_profile_images`");
        await queryRunner.query("DROP INDEX `REL_2dcb777c05a94bf80fa045619a` ON `user_profile_images`");
        await queryRunner.query("DROP TABLE `user_profile_images`");
        await queryRunner.query("DROP INDEX `REL_3a5ace99268077a859527db1e7` ON `expression_settings`");
        await queryRunner.query("DROP TABLE `expression_settings`");
        await queryRunner.query("DROP TABLE `tags`");
        await queryRunner.query("DROP TABLE `vectors`");
        await queryRunner.query("DROP TABLE `scalars`");
        await queryRunner.query("DROP INDEX `REL_e8134bca23f6ae0b95ca5c401c` ON `user_oauths`");
        await queryRunner.query("DROP TABLE `user_oauths`");
        await queryRunner.query("DROP INDEX `REL_48576009c45cfe3d29e290f881` ON `edit_histories`");
        await queryRunner.query("DROP TABLE `edit_histories`");
        await queryRunner.query("DROP TABLE `teams`");
        await queryRunner.query("DROP TABLE `notice`");
    }

}
