version: "3.7"

services:
  mysql:
    container_name: ${CONTAINER_PREFIX}.${DEV_MYSQL_CONTAINER_NAME}
    image: mysql
    ports:
      - ${DEV_MYSQL_PORT}:3306
    volumes:
      - ${VOLUMNS_PATH}/${CONTAINER_PREFIX}.${DEV_MYSQL_CONTAINER_NAME}:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci  --log-bin-trust-function-creators=1
    environment:
      - MYSQL_ROOT_PASSWORD=${DEV_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DEV_MYSQL_SCHEME}
      - MYSQL_USER=${DEV_MYSQL_USER}
      - MYSQL_PASSWORD=${DEV_MYSQL_PASSWORD}
    restart: always

  redis:
    container_name: ${CONTAINER_PREFIX}.${DEV_REDIS_CONTAINER_NAME}
    image: redis
    ports:
      - ${DEV_REDIS_PORT}:6379
    volumes:
      - ${VOLUMNS_PATH}.${CONTAINER_PREFIX}.${DEV_REDIS_CONTAINER_NAME}:/data
    restart: always



