version: "3.7"

services:
  mysql:
    container_name: ${CONTAINER_PREFIX}.${MYSQL_CONTAINER_NAME}
    image: mysql
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ${VOLUMNS_PATH}/${CONTAINER_PREFIX}.${MYSQL_CONTAINER_NAME}:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci --log-bin-trust-function-creators=1
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_SCHEME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always

  redis:
    container_name: ${CONTAINER_PREFIX}.${REDIS_CONTAINER_NAME}
    image: redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ${VOLUMNS_PATH}/${CONTAINER_PREFIX}.${REDIS_CONTAINER_NAME}:/data
    restart: always

